//SEGMENT 1
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// sources: data.proto, enums.proto, webcast.proto
// plugin: python-betterproto
// This file has been @generated

import 'package:built_collection/built_collection.dart';
import 'package:better_enum/better_enum.dart';

enum AuditStatus {
  AUDITSTATUSUNKNOWN,
  AUDITSTATUSPASS,
  AUDITSTATUSFAILED,
  AUDITSTATUSREVIEWING,
  AUDITSTATUSFORBIDDEN,
}

enum EmoteType {
  EMOTETYPENORMAL,
  EMOTETYPEWITHSTICKER,
}

enum ContentSource {
  CONTENTSOURCEUNKNOWN,
  CONTENTSOURCENORMAL,
  CONTENTSOURCECAMERA,
}

enum EmotePrivateType {
  NORMAL,
  SUB_WAVE,
}

enum TextType {
  DISPLAY_TEXT,
  CONTENT,
}

enum LinkmicApplierSortSetting {
  NONE,
  BY_GIFT_SCORE,
}

enum HashtagNamespace {
  GLOBAL,
  GAMING,
}

enum AgreeStatus {
  AGREE_UNKNOWN,
  AGREE,
  REJECT,
}

enum KickoutReason {
  UNKNOWN,
  FIRST_FRAME_TIMEOUT,
  BY_HOST,
  RTC_LOST_CONNECTION,
  BY_PUNISH,
  BY_ADMIN,
  HOST_REMOVE_ALL_GUESTS,
}

enum GroupStatus {
  UNKNOWN,
  WAITING,
  LINKED,
}

enum BusinessCase {
  BUSINESS_NOT_SET,
  APPLY_BIZ_CONTENT,
  INVITE_BIZ_CONTENT,
  REPLY_BIZ_CONTENT,
  PERMIT_BIZ_CONTENT,
  JOIN_DIRECT_BIZ_CONTENT,
  KICK_OUT_BIZ_CONTENT,
  LIST_CHANGE_BIZ_CONTENT,
  MULTI_LIVE_CONTENT,
  COHOST_CONTENT,
}

enum ReplyStatus {
  UNKNOWN,
  AGREE,
  REFUSE_PERSONALLY,
  REFUSE_TYPE_NOT_SUPPORT,
  REFUSE_PROCESSING_INVITATION,
  REFUSE_BY_TIMEOUT,
  REFUSE_EXCEPTION,
  REFUSE_SYSTEM_NOT_SUPPORTED,
  REFUSE_SUBTYPE_DIFFERENCE,
  REFUSE_IN_MICROOM,
  REFUSE_NOT_LOAD_PLUGIN,
  REFUSE_IN_MULTI_GUEST,
  REFUSE_PAUSE_LIVE,
  REFUSE_OPEN_CAMERA_DIALOG_SHOWING,
  REFUSE_DRAW_GUESSING,
  REFUSE_RANDOM_MATCHING,
  REFUSE_IN_MATCH_PROCESSING,
  REFUSE_IN_MICROOM_FOR_MULTI_COHOST,
  REFUSE_COHOST_FINISHED,
  REFUSE_NOT_CONNECTED,
  REFUSE_LINKMIC_FULL,
  REFUSE_ARC_INCOMPATIBLE,
  REFUSE_PROCESSING_OTHER_INVITE,
  REFUSE_PROCESSING_OTHER_APPLY,
  REFUSE_IN_ANCHOR_COHOST,
  REFUSE_TOPIC_PAIRING,
}
//SEGMENT 2
enum ReplyStatus {
  // Previous enum values...

  REFUSE_LINKMIC_FULL,
  REFUSE_ARC_INCOMPATIBLE,
  REFUSE_PROCESSING_OTHER_INVITE,
  REFUSE_PROCESSING_OTHER_APPLY,
  REFUSE_IN_ANCHOR_COHOST,
  REFUSE_TOPIC_PAIRING,
}

enum SubscribeType {
  SUBSCRIBETYPE_ONCE,
  SUBSCRIBETYPE_AUTO,
  SUBSCRIBETYPE_DEFAULT,
}

enum OldSubscribeStatus {
  OLDSUBSCRIBESTATUS_FIRST,
  OLDSUBSCRIBESTATUS_RESUB,
  OLDSUBSCRIBESTATUS_SUBINGRACEPERIOD,
  OLDSUBSCRIBESTATUS_SUBNOTINGRACEPERIOD,
  OLDSUBSCRIBESTATUS_DEFAULT,
}

enum SubscribingStatus {
  SUBSCRIBINGSTATUS_UNKNOWN,
  SUBSCRIBINGSTATUS_ONCE,
  SUBSCRIBINGSTATUS_CIRCLE,
  SUBSCRIBINGSTATUS_CIRCLECANCEL,
  SUBSCRIBINGSTATUS_REFUND,
  SUBSCRIBINGSTATUS_INGRACEPERIOD,
  SUBSCRIBINGSTATUS_NOTINGRACEPERIOD,
}

enum LinkmicStatus {
  Disable,
  Enable,
  Just_Following,
  Multi_Linking,
  Multi_Linking_Only_Following,
}

enum MemberMessageAction {
  UNKNOWN,
  JOINED,
  SUBSCRIBED,
}

enum ControlAction {
  ControlActionUNKNOWN,
  STREAM_PAUSED,
  STREAM_UNPAUSED,
  STREAM_ENDED,
}

enum LinkLayerMessageType {
  Linker_Unknown,
  Linker_Create,
  Linker_Invite,
  Linker_Apply,
  Linker_Permit,
  Linker_Reply,
  Linker_Kick_Out,
  Linker_Cancel_Apply,
  Linker_Cancel_Invite,
  Linker_Leave,
  Linker_Finish,
  Linker_List_Change,
  Linker_Join_Direct,
  Linker_Join_Group,
  Linker_Permit_Group,
  Linker_Cancel_Group,
  Linker_Leave_Group,
  Linker_P2P_Group_Change,
  Linker_Group_Change,
}

enum BarrageType {
  BarrageType_Unknown,
  EComOrdering,
  EComBuying,
  Normal,
  Subscribe,
  EventView,
  EventRegistered,
  SubscribeGift,
  UserUpgrade,
  GradeUserEntranceNotification,
  FansLevelUpgrade,
  FansLevelEntrance,
  GamePartnership,
}

enum EnvelopeBusinessType {
  BusinessTypeUnknown,
  BusinessTypeUserDiamond,
  BusinessTypePlatformDiamond,
  BusinessTypePlatformShell,
  BusinessTypePortal,
  BusinessTypePlatformMerch,
  BusinessTypeEoYDiamond,
  BusinessTypeFanClubGtM,
}

enum EnvelopeFollowShowStatus {
  EnvelopeFollowShowUnknown,
  EnvelopeFollowShow,
  EnvelopeFollowNotShow,
}

enum EnvelopeDisplay {
  EnvelopeDisplayUnknown,
  EnvelopeDisplayNew,
  EnvelopeDisplayHide,
}
//SEGMENT 3
enum EnvelopeFollowShowStatus {
  EnvelopeFollowShowUnknown,
  EnvelopeFollowShow,
  EnvelopeFollowNotShow,
}

enum EnvelopeDisplay {
  EnvelopeDisplayUnknown,
  EnvelopeDisplayNew,
  EnvelopeDisplayHide,
}

enum CommonContentCase {
  COMMON_CONTENT_NOT_SET,
  CREATE_CHANNEL_CONTENT,
  LIST_CHANGE_CONTENT,
  INVITE_CONTENT,
  APPLY_CONTENT,
  PERMIT_APPLY_CONTENT,
  REPLY_INVITE_CONTENT,
  KICK_OUT_CONTENT,
  CANCEL_APPLY_CONTENT,
  CANCEL_INVITE_CONTENT,
  LEAVE_CONTENT,
  FINISH_CONTENT,
  JOIN_DIRECT_CONTENT,
  JOIN_GROUP_CONTENT,
  PERMIT_GROUP_CONTENT,
  CANCEL_GROUP_CONTENT,
  LEAVE_GROUP_CONTENT,
  P2P_GROUP_CHANGE_CONTENT,
  GROUP_CHANGE_CONTENT,
}

enum LinkMessageType {
  TPYE_LINKER_UNKNOWN,
  TYPE_LINKER_CREATE,
  TYPE_LINKER_CLOSE,
  TYPE_LINKER_INVITE,
  TYPE_LINKER_APPLY,
  TYPE_LINKER_REPLY,
  TPYE_LINKER_ENTER,
  TPYE_LINKER_LEAVE,
  TYPE_LINKER_PERMIT,
  TPYE_LINKER_CANCEL_INVITE,
  TYPE_LINKER_WAITING_LIST_CHANGE,
  TYPE_LINKER_LINKED_LIST_CHANGE,
  TYPE_LINKER_UPDATE_USER,
  TPYE_LINKER_KICK_OUT,
  TPYE_LINKER_CANCEL_APPLY,
  TYPE_LINKER_MUTE,
  TYPE_LINKER_MATCH,
  TYPE_LINKER_UPDATE_USER_SETTING,
  TYPE_LINKER_MIC_IDX_UPDATE,
  TYPE_LINKER_LEAVE_V2,
  TYPE_LINKER_WAITING_LIST_CHANGE_V2,
  TYPE_LINKER_LINKED_LIST_CHANGE_V2,
  TYPE_LINKER_COHOST_LIST_CHANGE,
  TYPE_LINKER_MEDIA_CHANGE,
  TYPE_LINKER_ACCEPT_NOTICE,
  TPYE_LINKER_SYS_KICK_OUT,
  TPYE_LINKMIC_USER_TOAST,
}

enum MessageType {
  MESSAGETYPE_SUBSUCCESS,
  MESSAGETYPE_ANCHORREMINDER,
  MESSAGETYPE_ENTERROOMEXPIRESOON,
  MESSAGETYPE_SUBGOALCREATETOANCHOR,
  MESSAGETYPE_SUBGOALCOMPLETETOAUDIENCE,
  MESSAGETYPE_SUBGOALCOMPLETETOANCHOR,
  MESSAGETYPE_SUBGIFTTIKTOK2USERNOTICE,
  MESSAGETYPE_SUBGIFTTIKTOK2ANCHORNOTICE,
  MESSAGETYPE_SUBGIFTTRECEIVESENDNOTICE,
  MESSAGETYPE_SUBGIFTSENDSUCCEEDROOMMESSAGE,
  MESSAGETYPE_SUBGIFTSENDSUCCEEDANCHORNOTICE,
  MESSAGETYPE_SUBGIFTLOWVERSIONUPGRADENOTICE,
  MESSAGETYPE_SUBGIFTUSERBUYAUTHNOTICE,
}

enum Scene {
  UNKNOWN,
  CO_HOST,
  MULTI_LIVE,
}
//SEGMENT 4
enum MessageType {
  // Previous enum values...

  MESSAGETYPE_SUBGIFTLOWVERSIONUPGRADENOTICE,
  MESSAGETYPE_SUBGIFTUSERBUYAUTHNOTICE,
}

enum Scene {
  // Previous enum values...

  CO_HOST,
  MULTI_LIVE,
}

enum CommonImDispatchStrategy {
  IM_DISPATCH_STRATEGY_DEFAULT,
  IM_DISPATCH_STRATEGY_BYPASS_DISPATCH_QUEUE,
}

enum BadgeStructDataCase {
  DATA_NOT_SET,
  IMAGE,
  TEXT,
  STR,
  COMBINE,
}

enum BadgeStructBadgeDisplayType {
  BADGEDISPLAYTYPE_UNKNOWN,
  BADGEDISPLAYTYPE_IMAGE,
  BADGEDISPLAYTYPE_TEXT,
  BADGEDISPLAYTYPE_STRING,
  BADGEDISPLAYTYPE_COMBINE,
}

enum BadgeStructPosition {
  POSITIONUNKNOWN,
  POSITIONLEFT,
  POSITIONRIGHT,
}

enum UserLiveEventInfoEventPayMethod {
  EVENTPAYMETHODINVALID,
  EVENTPAYMETHODCOINS,
  EVENTPAYMETHODCASH,
}

enum UserEcommerceEntranceCreatorType {
  UNDEFINED,
  OFFICIAL,
  MARKET,
  NORMAL,
}

enum UserEcommerceEntranceEntranceType {
  PROFILE,
  SHOWCASE,
  SHOP,
}

enum UserEcommerceEntranceShopEntranceInfoStoreLabelStoreBrandLabelType {
  NONE,
  OFFICIAL,
  AUTHORIZED,
  STORE_BRAND_LABEL_TYPE_BLUE_V,
  STORE_BRAND_LABEL_TYPE_TOP_CHOICE,
}

enum UserFansClubPreferntialType {
  PRESONALPROFILE,
  OTHERROOM,
}

enum UserFansClubFansClubDataBadgeIcon {
  UNKNOWN,
  ICON,
  SMALLICON,
}

enum UserFansClubFansClubDataUserFansClubStatus {
  NOTJOINED,
  ACTIVE,
  INACTIVE,
}

enum ListUserLinkType {
  LINK_UNKNOWN,
  AUDIO,
  VIDEO,
}

enum WebcastBarrageMessageBarrageType {
  UNKNOWN,
  ECOMORDERING,
  ECOMBUYING,
  NORMAL,
  SUBSCRIBE,
  EVENTVIEW,
  EVENTREGISTERED,
  SUBSCRIBEGIFT,
  USERUPGRADE,
  GRADEUSERENTRANCENOTIFICATION,
  FANSLEVELUPGRADE,
  FANSLEVELENTRANCE,
  GAMEPARTNERSHIP,
}

@dataclass
class Common extends BetterProtoMessage {
  String method = 1;
  int msgId = 2;
  int roomId = 3;
  int createTime = 4;
  int monitor = 5;
  bool isShowMsg = 6;
  String describe = 7;
  Text displayText = 8;
  int foldType = 9;
  int anchorFoldType = 10;
}
//SEGMENT 5
@dataclass
class Common extends BetterProtoMessage {
  String method = 1;
  int msgId = 2;
  int roomId = 3;
  int createTime = 4;
  int monitor = 5;
  bool isShowMsg = 6;
  String describe = 7;
  Text displayText = 8;
  int foldType = 9;
  int anchorFoldType = 10;
  int priorityScore = 11;
  String logId = 12;
  String msgProcessFilterK = 13;
  String msgProcessFilterV = 14;
  String fromIdc = 15;
  String toIdc = 16;
  List<String> filterMsgTagsList = 17;
  CommonLiveMessageSei sei = 18;
  CommonLiveMessageId dependRootId = 19;
  CommonLiveMessageId dependId = 20;
  int anchorPriorityScore = 21;
  int roomMessageHeatLevel = 22;
  int foldTypeForWeb = 23;
  int anchorFoldTypeForWeb = 24;
  int clientSendTime = 25;
  CommonImDispatchStrategy dispatchStrategy = 26;
}

@dataclass
class CommonLiveMessageSei extends BetterProtoMessage {
  CommonLiveMessageId uniqueId = 1;
  int timestamp = 2;
}

@dataclass
class CommonLiveMessageId extends BetterProtoMessage {
  String primaryId = 1;
  String messageScene = 2;
}

@dataclass
class Text extends BetterProtoMessage {
  String key = 1;
  String defaultPattern = 2;
  TextTextFormat defaultFormat = 3;
  List<TextTextPiece> piecesList = 4;
}

@dataclass
class TextTextPiece extends BetterProtoMessage {
  int type = 1;
  TextTextFormat format = 2;
  String stringValue = 11;
  TextTextPieceUser userValue = 21;
  TextTextPieceGift giftValue = 22;
  TextTextPiecePatternRef patternRefValue = 24;
}

@dataclass
class TextTextFormat extends BetterProtoMessage {
  String color = 1;
  bool bold = 2;
  bool italic = 3;
  int weight = 4;
  int italicAngle = 5;
  int fontSize = 6;
  bool useHeighLightColor = 7;
  bool useRemoteClor = 8;
}

@dataclass
class TextTextPieceGift extends BetterProtoMessage {
  int giftId = 1;
  int colorId = 4;
}
//SEGMENT 6
@dataclass
class TextTextPieceGift extends BetterProtoMessage {
  int giftId = 1;
  int colorId = 4;
}

@dataclass
class TextTextPiecePatternRef extends BetterProtoMessage {
  String key = 1;
  String defaultPattern = 2;
}

@dataclass
class TextTextPieceUser extends BetterProtoMessage {
  User user = 1;
  bool withColon = 2;
}

@dataclass
class Image extends BetterProtoMessage {
  List<String> urlList = 1;
  bool isAnimated = 9;
}

@dataclass
class BadgeStruct extends BetterProtoMessage {
  BadgeStructBadgeDisplayType displayType = 1;
  BadgeStructImageBadge image = 20;
  BadgeStructTextBadge text = 21;
  BadgeStructStringBadge str = 22;
  BadgeStructCombineBadge combine = 23;
}

@dataclass
class BadgeStructCombineBadge extends BetterProtoMessage {
  Image icon = 2;
  BadgeStructTextBadge text = 3;
  String str = 4;
  BadgeStructProfileCardPanel profileCardPanel = 7;
  BadgeStructCombineBadgeBackground background = 11;
  BadgeStructCombineBadgeBackground backgroundDarkMode = 12;
  bool iconAutoMirrored = 13;
  bool backgroundAutoMirrored = 14;
  int publicScreenShowStyle = 15;
  int personalCardShowStyle = 16;
  int ranklistOnlineAudienceShowStyle = 17;
  int multiGuestShowStyle = 18;
}

@dataclass
class BadgeStructProfileContent extends BetterProtoMessage {
  bool useContent = 1;
  List<BadgeStructIconConfig> iconList = 2;
  BadgeStructNumberConfig numberConfig = 3;
}

@dataclass
class BadgeStructProjectionConfig extends BetterProtoMessage {
  bool useProjection = 1;
  Image icon = 2;
}

@dataclass
class BadgeStructNumberConfig extends BetterProtoMessage {
  int number = 1;
  BadgeStructCombineBadgeBackground background = 3;
}

@dataclass
class BadgeStructProfileCardPanel extends BetterProtoMessage {
  bool useNewProfileCardStyle = 1;
  BadgeStructProjectionConfig projectionConfig = 3;
  BadgeStructProfileContent profileContent = 4;
}
//SEGMENT 7
@dataclass
class BadgeStructProfileCardPanel extends BetterProtoMessage {
  bool useNewProfileCardStyle = 1;
  BadgeStructProjectionConfig projectionConfig = 3;
  BadgeStructProfileContent profileContent = 4;
}

@dataclass
class BadgeStructCombineBadgeBackground extends BetterProtoMessage {
  Image image = 1;
  String backgroundColorCode = 2;
  String borderColorCode = 3;
}

@dataclass
class BadgeStructImageBadge extends BetterProtoMessage {
  Image image = 2;
}

@dataclass
class BadgeStructTextBadge extends BetterProtoMessage {
  String defaultPattern = 3;
}

@dataclass
class BadgeStructIconConfig extends BetterProtoMessage {
  Image icon = 1;
  BadgeStructCombineBadgeBackground background = 2;
}

@dataclass
class BadgeStructStringBadge extends BetterProtoMessage {
  String str = 2;
}

@dataclass
class GiftStruct extends BetterProtoMessage {
  Image image = 1;
  String describe = 2;
  int duration = 4;
  int id = 5;
  bool forLinkmic = 7;
  bool combo = 10;
  int type = 11;
  int diamondCount = 12;
  bool isDisplayedOnPanel = 13;
  int primaryEffectId = 14;
  Image giftLabelIcon = 15;
  String name = 16;
  Image icon = 21;
  String goldEffect = 24;
  Image previewImage = 47;
  GiftStructGiftPanelBanner giftPanelBanner = 48;
  bool isBroadcastGift = 49;
  bool isEffectBefview = 50;
  bool isRandomGift = 51;
  bool isBoxGift = 52;
  bool canPutInGiftBox = 53;
}

@dataclass
class GiftStructGiftPanelBanner extends BetterProtoMessage {
  Text displayText = 1;
  Image leftIcon = 2;
  String schemaUrl = 3;
  List<String> bgColorValuesList = 5;
  String bannerLynxUrl = 6;
}

@dataclass
class GiftStructGiftRandomEffectInfo extends BetterProtoMessage {
  GiftStructRandomGiftPanelBanner randomGiftPanelBanner = 1;
  List<int> effectIdsList = 2;
  String hostKey = 3;
  String audienceKey = 4;
  GiftStructRandomGiftBubble randomGiftBubble = 5;
}
//SEGMENT 8
@dataclass
class GiftStructRandomGiftBubble extends BetterProtoMessage {
  String displayText = 1;
  Image iconDynamicEffect = 2;
}

@dataclass
class GiftStructRandomGiftPanelBanner extends BetterProtoMessage {
  Image bgImage = 1;
  Image shadingImage = 2;
  int targetNum = 3;
  int collectNum = 4;
  String displayText = 5;
  Image leftIcon = 6;
  String schemaUrl = 7;
  List<String> bgColorValuesList = 8;
  int round = 9;
}

@dataclass
class User extends BetterProtoMessage {
  int id = 1;
  String nickname = 3;
  String bioDescription = 5;
  Image avatarThumb = 9;
  Image avatarMedium = 10;
  Image avatarLarge = 11;
  bool verified = 12;
  int status = 15;
  int createTime = 16;
  int modifyTime = 17;
  int secret = 18;
  String shareQrcodeUri = 19;
  List<Image> badgeImageList = 21;
  UserFollowInfo followInfo = 22;
  UserPayGrade payGrade = 23;
  UserFansClub fansClub = 24;
  UserBorder border = 25;
  String specialId = 26;
  Image avatarBorder = 27;
  Image medal = 28;
  List<Image> realTimeIconsList = 29;
  List<Image> newRealTimeIconsList = 30;
  int topVipNo = 31;
  UserUserAttr userAttr = 32;
  UserOwnRoom ownRoom = 33;
  int payScore = 34;
  int ticketCount = 35;
  LinkmicStatus linkMicStats = 37;
  String displayId = 38;
  bool withCommercePermission = 39;
  bool withFusionShopEntry = 40;
  UserAnchorLevel webcastAnchorLevel = 42;
  String verifiedContent = 43;
  UserAuthorStats authorStats = 44;
  List<User> topFansList = 45;
  String secUid = 46;
}
//SEGMENT 9
@dataclass
class User extends BetterProtoMessage {
  int id = 1;
  String nickname = 3;
  String bioDescription = 5;
  Image avatarThumb = 9;
  Image avatarMedium = 10;
  Image avatarLarge = 11;
  bool verified = 12;
  int status = 15;
  int createTime = 16;
  int modifyTime = 17;
  int secret = 18;
  String shareQrcodeUri = 19;
  List<Image> badgeImageList = 21;
  UserFollowInfo followInfo = 22;
  UserPayGrade payGrade = 23;
  UserFansClub fansClub = 24;
  UserBorder border = 25;
  String specialId = 26;
  Image avatarBorder = 27;
  Image medal = 28;
  List<Image> realTimeIconsList = 29;
  List<Image> newRealTimeIconsList = 30;
  int topVipNo = 31;
  UserUserAttr userAttr = 32;
  UserOwnRoom ownRoom = 33;
  int payScore = 34;
  int ticketCount = 35;
  LinkmicStatus linkMicStats = 37;
  String displayId = 38;
  bool withCommercePermission = 39;
  bool withFusionShopEntry = 40;
  UserAnchorLevel webcastAnchorLevel = 42;
  String verifiedContent = 43;
  UserAuthorStats authorStats = 44;
  List<User> topFansList = 45;
  String secUid = 46;
  int userRole = 47;
  UserActivityInfo activityReward = 49;
  Image personalCard = 52;
  UserAuthenticationInfo authenticationInfo = 53;
  List<Image> mediaBadgeImageList = 57;
  List<int> commerceWebcastConfigIdsList = 60;
  List<UserBorder> borderList = 61;
  UserComboBadgeInfo comboBadgeInfo = 62;
  UserSubscribeInfo subscribeInfo = 63;
  List<BadgeStruct> badgeList = 64;
  List<int> mintTypeLabelList = 65;
  UserFansClubInfo fansClubInfo = 66;
  bool allowFindByContacts = 1002;
  bool allowOthersDownloadVideo = 1003;
  bool allowOthersDownloadWhenSharingVideo = 1004;
  bool allowShareShowProfile = 1005;
  bool allowShowInGossip = 1006;
  bool allowShowMyAction = 1007;
  bool allowStrangeComment = 1008;
  bool allowUnfollowerComment = 1009;
  bool allowUseLinkmic = 1010;
  UserAnchorLevel anchorLevel = 1011;
  Image avatarJpg = 1012;
  String bgImgUrl = 1013;
  int blockStatus = 1016;
  int commentRestrict = 1017;
  String constellation = 1018;
  int disableIchat = 1019;
  int enableIchatImg = 1020;
  int exp = 1021;
  int fanTicketCount = 1022;
  bool foldStrangerChat = 1023;
  int followStatus = 1024;
  int ichatRestrictType = 1027;
  String idStr = 1028;
  bool isFollower = 1029;
  bool isFollowing = 1030;
  bool needProfileGuide = 1031;
  int payScores = 1032;
  bool pushCommentStatus = 1033;
  bool pushDigg = 1034;
  bool pushFollow = 1035;
  bool pushFriendAction = 1036;
  bool pushIchat = 1037;
  bool pushStatus = 1038;
  bool pushVideoPost = 1039;
  bool pushVideoRecommend = 1040;
  UserUserStats stats = 1041;
  String verifiedReason = 1043;
}
//SEGMENT 10
@dataclass
class User extends BetterProtoMessage {
  int id = 1;
  String nickname = 3;
  String bioDescription = 5;
  Image avatarThumb = 9;
  Image avatarMedium = 10;
  Image avatarLarge = 11;
  bool verified = 12;
  int status = 15;
  int createTime = 16;
  int modifyTime = 17;
  int secret = 18;
  String shareQrcodeUri = 19;
  List<Image> badgeImageList = 21;
  UserFollowInfo followInfo = 22;
  UserPayGrade payGrade = 23;
  UserFansClub fansClub = 24;
  UserBorder border = 25;
  String specialId = 26;
  Image avatarBorder = 27;
  Image medal = 28;
  List<Image> realTimeIconsList = 29;
  List<Image> newRealTimeIconsList = 30;
  int topVipNo = 31;
  UserUserAttr userAttr = 32;
  UserOwnRoom ownRoom = 33;
  int payScore = 34;
  int ticketCount = 35;
  LinkmicStatus linkMicStats = 37;
  String displayId = 38;
  bool withCommercePermission = 39;
  bool withFusionShopEntry = 40;
  UserAnchorLevel webcastAnchorLevel = 42;
  String verifiedContent = 43;
  UserAuthorStats authorStats = 44;
  List<User> topFansList = 45;
  String secUid = 46;
  int userRole = 47;
  UserActivityInfo activityReward = 49;
  Image personalCard = 52;
  UserAuthenticationInfo authenticationInfo = 53;
  List<Image> mediaBadgeImageList = 57;
  List<int> commerceWebcastConfigIdsList = 60;
  List<UserBorder> borderList = 61;
  UserComboBadgeInfo comboBadgeInfo = 62;
  UserSubscribeInfo subscribeInfo = 63;
  List<BadgeStruct> badgeList = 64;
  List<int> mintTypeLabelList = 65;
  UserFansClubInfo fansClubInfo = 66;
  bool allowFindByContacts = 1002;
  bool allowOthersDownloadVideo = 1003;
  bool allowOthersDownloadWhenSharingVideo = 1004;
  bool allowShareShowProfile = 1005;
  bool allowShowInGossip = 1006;
  bool allowShowMyAction = 1007;
  bool allowStrangeComment = 1008;
  bool allowUnfollowerComment = 1009;
  bool allowUseLinkmic = 1010;
  UserAnchorLevel anchorLevel = 1011;
  Image avatarJpg = 1012;
  String bgImgUrl = 1013;
  int blockStatus = 1016;
  int commentRestrict = 1017;
  String constellation = 1018;
  int disableIchat = 1019;
  int enableIchatImg = 1020;
  int exp = 1021;
  int fanTicketCount = 1022;
  bool foldStrangerChat = 1023;
  int followStatus = 1024;
  int ichatRestrictType = 1027;
  String idStr = 1028;
  bool isFollower = 1029;
  bool isFollowing = 1030;
  bool needProfileGuide = 1031;
  int payScores = 1032;
  bool pushCommentStatus = 1033;
  bool pushDigg = 1034;
  bool pushFollow = 1035;
  bool pushFriendAction = 1036;
  bool pushIchat = 1037;
  bool pushStatus = 1038;
  bool pushVideoPost = 1039;
  bool pushVideoRecommend = 1040;
  UserUserStats stats = 1041;
  String verifiedReason = 1043;
  bool withCarManagementPermission = 1044;
  List<UserLiveEventInfo> upcomingEventList = 1045;
  String scmLabel = 1046;
  UserEcommerceEntrance ecommerceEntrance = 1047;
  bool isBlock = 1048;
}

@dataclass
class UserLiveEventInfo extends BetterProtoMessage {
  int eventId = 1;
  int startTime = 2;
  int duration = 3;
  String title = 4;
  String description = 5;
  bool hasSubscribed = 6;
  bool isPaidEvent = 7;
  int ticketAmount = 8;
  int payMethod = 9;
}

@dataclass
class UserLiveEventInfoWalletPackage extends BetterProtoMessage {
  String iapId = 1;
  String usdPriceShow = 2;
}

@dataclass
class UserActivityInfo extends BetterProtoMessage {
  Image badge = 1;
  Image storytag = 2;
}

@dataclass
class UserAnchorLevel extends BetterProtoMessage {
  int level = 1;
  int experience = 2;
  int lowestExperienceThisLevel = 3;
  int highestExperienceThisLevel = 4;
  int taskStartExperience = 5;
  int taskStartTime = 6;
  int taskDecreaseExperience = 7;
  int taskTargetExperience = 8;
  int taskEndTime = 9;
  Image profileDialogBg = 10;
  Image profileDialogBgBack = 11;
  Image stageLevel = 12;
  Image smallIcon = 13;
}

@dataclass
class UserAuthenticationInfo extends BetterProtoMessage {
  String customVerify = 1;
  String enterpriseVerifyReason = 2;
  Image authenticationBadge = 3;
}

@dataclass
class UserAuthorStats extends BetterProtoMessage {
  int videoTotalCount = 1;
  int videoTotalPlayCount = 2;
  int videoTotalShareCount = 3;
  int videoTotalSeriesCount = 4;
  int varietyShowPlayCount = 5;
  int videoTotalFavoriteCount = 6;
}
//SEGMENT 11
@dataclass
class UserBorder extends BetterProtoMessage {
  Image icon = 1;
  int level = 2;
  String source = 3;
  Image profileDecorationRibbon = 4;
  String avatarBackgroundColor = 7;
  String avatarBackgroundBorderColor = 8;
}

@dataclass
class UserComboBadgeInfo extends BetterProtoMessage {
  Image icon = 1;
  int comboCount = 2;
}

@dataclass
class UserEcommerceEntrance extends BetterProtoMessage {
  UserEcommerceEntranceEntranceType entranceType = 1;
  UserEcommerceEntranceCreatorType creatorType = 2;
  String schema = 3;
  UserEcommerceEntranceShopEntranceInfo shopEntranceInfo = 4;
  UserEcommerceEntranceShowcaseEntranceInfo showcaseEntranceInfo = 5;
}

@dataclass
class UserEcommerceEntranceShopEntranceInfo extends BetterProtoMessage {
  String shopId = 1;
  String shopName = 2;
  String shopRating = 3;
  UserEcommerceEntranceShopEntranceInfoStoreLabel storeLabel = 4;
  String formatSoldCount = 5;
  int soldCount = 6;
  int expRatePercentile = 7;
  String expRateTopDisplay = 8;
  int rateDisplayStyle = 9;
  bool showRateNotApplicable = 10;
}

@dataclass
class UserEcommerceEntranceShopEntranceInfoStoreLabel extends BetterProtoMessage {
  UserEcommerceEntranceShopEntranceInfoStoreLabelStoreOfficialLabel officialLabel = 1;
  bool isBytemall = 2;
}

@dataclass
class UserEcommerceEntranceShopEntranceInfoStoreLabelStoreOfficialLabel extends BetterProtoMessage {
  UserEcommerceEntranceShopEntranceInfoStoreLabelStoreOfficialLabelShopLabelImage labelImageLight = 1;
  UserEcommerceEntranceShopEntranceInfoStoreLabelStoreOfficialLabelShopLabelImage labelImageDark = 2;
  int labelType = 3;
  String labelTypeStr = 4;
}

@dataclass
class UserEcommerceEntranceShopEntranceInfoStoreLabelStoreOfficialLabelShopLabelImage extends BetterProtoMessage {
  int height = 1;
  int width = 2;
  String minetype = 3;
  String thumbUri = 4;
  List<String> thumbUriList = 5;
}
//SEGMENT 12
@dataclass
class UserEcommerceEntranceShopEntranceInfoStoreLabelStoreOfficialLabelShopLabelImage extends BetterProtoMessage {
  int height = 1;
  int width = 2;
  String minetype = 3;
  String thumbUri = 4;
  List<String> thumbUriList = 5;
  String uri = 6;
  List<String> urlList = 7;
  String color = 8;
}

@dataclass
class UserEcommerceEntranceShowcaseEntranceInfo extends BetterProtoMessage {
  String formatSoldCount = 1;
  int soldCount = 2;
}

@dataclass
class UserFansClub extends BetterProtoMessage {
  UserFansClubFansClubData data = 1;
}
//SEGMENT 13
